rationalizing buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -28,6 +28,7 @@ export CONFIG_DIR=$3
 unset GIT_DIR
 
 # Syntactic starch (more complex)
+# Note '-d' doesnt match hidden dirs
 for f in $(ls -d $BIN_DIR/utils.d/*); do source $f; done
 
 # check if i got the right PATH form last buildpack
@@ -88,18 +89,19 @@ for d in $LINUXBREW_DIRS; do
 
     if [ $PACKAGE_BUILDER_REINSTALL_LINUXBREW -gt 0 ]; then
 
-        do-debug "Deleting cache $d"
-        rm -rf $CACHE_DIR/$d || true
+        do-debug "Deleting cache $d and ${d}.tar.lz4"
+        rm -rf $CACHE_DIR/$d $CACHE_DIR/${d}.tar.lz4 || true
         # show_files "$CACHE_DIR/"
 
     else
 
-        do-debug "Moving $CACHE_DIR/$d to $CURR_DIR"
-        cp -af $CACHE_DIR/$d $PWD/ || true
+#        do-debug "Moving $CACHE_DIR/$d to $CURR_DIR"
+#        cp -af $CACHE_DIR/$d $PWD/ || true
+        decompress_to_builddir $CACHE_DIR/${d}.tar.lz4
         # show_files $PWD/$d
 
-        do-debug "Deleting old cache $CACHE_DIR/$d"
-        rm -rf $CACHE_DIR/$d || true
+#        do-debug "Deleting old cache $CACHE_DIR/$d"
+#        rm -rf $CACHE_DIR/$d || true
         # show_files "$CACHE_DIR/"
 
     fi
@@ -126,8 +128,9 @@ export INFOPATH=$OLD_INFOPATH; do-debug "INFOPATH reset to '$INFOPATH'"
 
 # Copy the new linuxbrew directories to CACHE_DIR
 for d in $LINUXBREW_DIRS; do
-    do-debug "Copying $d to $PWD"
-    cp -af "$d" "$CACHE_DIR"  # if it fails here then the build should fail
+#    do-debug "Copying $d to $PWD"
+#    cp -af "$d" "$CACHE_DIR"  # if it fails here then the build should fail
+    compress_to_cache "$d"
 done
 
 # empty the local .cache to save space
