expand 'brew_wait' into 'proc_watcher' so any long running process can use it

diff --git a/bin/utils.d/10_utils-extra b/bin/utils.d/10_utils-extra
--- a/bin/utils.d/10_utils-extra
+++ b/bin/utils.d/10_utils-extra
@@ -277,6 +277,9 @@ function proper_word() {
 
 function proc_watcher() {
 
+    ## IMPORTANT:
+    #  If an argument has "quotes" or 'quotes' the arguments should be passed as \"quotes\" or \'quotes\'
+
     ## This thing does:
     # 1.) Traps the brew process id
     # 2.) Sends it to the background
@@ -311,16 +314,20 @@ function proc_watcher() {
     assign_job_vars() {  # used in 'jobs -x'
         JOB_ID=$1
         JOB_PID=$(jobs -p %${JOB_ID})
-        do-debug "jobs -l:"
+        echo_debug "jobs -l:"
         jobs -l |& indent-debug
-        do-debug "JOB_ID=$JOB_ID"
-        do-debug "JOB_PID=$JOB_PID"
+        echo_debug "JOB_ID=$JOB_ID"
+        echo_debug "JOB_PID=$JOB_PID"
     }
     pid_exists() {
         echo $(kill -0 %${JOB_ID} |& grep --count .)
     }
+    # these are necessary because any indentation is done when this function is called
+    echo_debug() {
+        [ ${BUILD_DEBUG:-$BUILD_DEBUG_DEFAULT} -gt 0 ] && echo "DEBUG: $@" || return $?
+    }
 
-    puts-step "Running '$@' in ${FUNCNAME[0]}"
+    echo "Running '$@' in ${FUNCNAME[0]}"
     $@ |& brew_outputhandler &  # <-- raw execute whatever was passed <-- <-- <--
     jobs -x assign_job_vars %+
 
@@ -332,14 +339,14 @@ function proc_watcher() {
         if [ ${TIME_REMAINING} -gt 0 -a ${TIME_REMAINING} -le ${LAST_SLEEP_TIME} ]; then
 
             # 3c-i-1.)
-            puts-wait "$(date --date=@${TIME_REMAINING} +'%M:%S') until abort"
+            echo "..... $(date --date=@${TIME_REMAINING} +'%M:%S') until abort"
             set_sleep_time
 
         # 3c-ii.)
         elif [ ${TIME_REMAINING} -le 0 ]; then
 
             # 3c-ii-1.)
-            puts-warn 'Out of time!!'
+            echo '! Out of time!'
             declare -u KILLSIG
             while [ 1 ]; do
 
@@ -348,7 +355,7 @@ function proc_watcher() {
                     1) KILLSIG=SIGINT  ;;
                     2) KILLSIG=SIGABRT ;;
                     3) KILLSIG=SIGQUIT ;;
-                    *) puts-warn "Something's way wrong. Killing the program altogether with SIGKILL."
+                    *) echo "! Something's way wrong. Killing the program altogether with SIGKILL."
                        kill -SIGKILL %${JOB_ID} #&
                        RTN_STATUS=$?
                        sleep 5
@@ -356,7 +363,7 @@ function proc_watcher() {
                     ;;
                 esac
 
-                puts-warn "Aborting with $KILLSIG"
+                echo "! Aborting with $KILLSIG"
                 kill -${KILLSIG} %${JOB_ID} #&
                 RTN_STATUS=$?
 
@@ -369,13 +376,13 @@ function proc_watcher() {
     done
 
     # 3d.)
-    do-debug "Waiting on brew return status"
+    echo_debug "Waiting on brew return status"
     wait %${JOB_ID}
     declare -i WAIT_RTN_STATUS=$?
-    do-debug "WAIT_RTN_STATUS=$WAIT_RTN_STATUS"
+    echo_debug "WAIT_RTN_STATUS=$WAIT_RTN_STATUS"
 
     # 3e.)
     RTN_STATUS=${WAIT_RTN_STATUS:-$RTN_STATUS}
-    do-debug "Leaving ${FUNCNAME[0]} with RTN_STATUS = $RTN_STATUS"
+    echo_debug "Leaving ${FUNCNAME[0]} with RTN_STATUS = $RTN_STATUS"
     return ${RTN_STATUS}
 }
